---
- name: Deploy Scientific Calculator Container
  hosts: localhost
  become: false

  tasks:
    - name: Pull Docker Image
      command: /usr/local/bin/docker pull swayam614/scientific-calculator:latest

    - name: Stop existing container if running
      command: /usr/local/bin/docker stop scientific-calculator
      ignore_errors: yes

    - name: Remove old container
      command: /usr/local/bin/docker rm scientific-calculator
      ignore_errors: yes

    - name: Run new container
      command: /usr/local/bin/docker run -dit --name scientific-calculator swayam614/scientific-calculator:latest
